### ISSUE TITLE
✨ Enhancements  ✨

### ISSUE THREAD

**Issue by azdanov** [Aewass/Python-Password-Generator-w-TKinter-GUI#2]
Awesome job with the project!

Keep on coding and you'll get where you want to be. 👍 

A few things that I've noticed:

* **Separation of Concerns**. It is much easier to work, and upgrade your app when each "piece" of code is separate from one another (either in classes or just files.)
I see an opportunity to extract a separate GUI file, responsible for UI, PassGen file, responsible for the generation of the passwords, and Bootstrap/Main file, responsible for pulling it all together.

* **Copying the Password**. UX wise not being able to copy the generated password is a PITA.

* **User Friendliness**. It would be nice to have an easy to understand readme file which told me how to use this app, how to start/stop it, are there any dependencies, etc.

* **Simpler User Interface**. I understand that this was made as a training exercise, but the UI has too much redundant information. As a user, I want to generate a password and do it as fast and as easy as possible. Maybe hiding all the unneeded information and then showing it in a popup would be a better option?

* **Security**. `random.sample` is deterministic, although it is not used for generating tokens, I think it's still a good thing to use secure oriented functions when possible. [More Info](https://stackoverflow.com/questions/31356466/is-pythons-random-number-generation-easily-reproducible).

**Comment by Aewass** [comment]
Hi,

Thank you for the kind words.  Your advice is of great value for beginners like myself. 

I already shortened the code a bit and added some things that make sense more. 

As for your bullet points: 

- I agree, I'm still a bit unfamiliar with that, but I see how that is useful. I will update the code as soon as I make it work like that!

- Unfortunately I can't make Labels copy-able, I'll try to convert that widget to a Text widget, but that still creates a problem of calling a function in a Text widget -.-. That is a priority!

- Readme is a good idea. I'm also thinking of uploading an .exe of my PassGenerator and/or instruction on creating an exe with pip, powershell, etc. 

- Already made some changes to UI, will do more as soon as I figure out pack geometry or grid. 

- Thanks for the info. I understand that random module is actually pseudo random, more security is always useful.

Again, thank you for your insights and advice. I am really glad that people took time to review my code.
